# Generated by Django 5.1.1 on 2024-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "benedict_school",
            "0002_about_remove_parent_id_number_remove_parent_password_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="username",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="teacher_name",
        ),
        migrations.AddField(
            model_name="child",
            name="study_class",
            field=models.CharField(
                choices=[
                    ("baby_class", "Baby Class"),
                    ("middle_class", "Middle class"),
                    ("top_class", "Top class"),
                    ("primary_one", "Primary one"),
                    ("primary_two", "Primary two"),
                    ("primary_three", "Primary three"),
                    ("primary_four", "Primary four"),
                ],
                default="primary_one",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="ID_number",
            field=models.CharField(default="Unknown", max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
