# Generated by Django 5.1.1 on 2024-12-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0003_delete_activity_rename_username_staff_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parent",
            old_name="profile_image",
            new_name="parent_image",
        ),
        migrations.AlterField(
            model_name="parent",
            name="ID_number",
            field=models.CharField(default="", max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="parent",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="parent",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
