# Generated by Django 5.1.1 on 2024-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0005_galleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="tel_no",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="staff",
            name="tel_no",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="staff",
            name="ID_number",
            field=models.CharField(default="", max_length=14, unique=True),
        ),
    ]
