# Generated by Django 5.1.1 on 2024-12-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0006_parent_tel_no_staff_tel_no_alter_staff_id_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="description",
        ),
        migrations.AddField(
            model_name="about",
            name="title",
            field=models.CharField(default="Our School Anthem", max_length=255),
        ),
        migrations.AlterField(
            model_name="about",
            name="anthem",
            field=models.TextField(
                help_text="Write the anthem with each stanza separated by a new line."
            ),
        ),
    ]
