# Generated by Django 4.2.17 on 2025-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0009_remove_child_application_status_child_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
