# Generated by Django 5.1.1 on 2025-01-07 14:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0010_alter_staff_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "ordering": ["name", "role"],
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="address",
            field=models.TextField(
                default="No Address", help_text="Physical address of residence"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="bank_account_name",
            field=models.CharField(
                default="",
                help_text="Name as it appears on bank account",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="bank_account_number",
            field=models.CharField(
                default="",
                help_text="Bank account number for salary payment",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="bank_name",
            field=models.CharField(
                default="", help_text="Name of the bank", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="certificates",
            field=models.FileField(
                blank=True,
                help_text="Scanned copies of certificates",
                null=True,
                upload_to="staff_certificates/",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="date_hired",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date when staff member was hired",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="date_of_birth",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date of birth of the staff member",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="emergency_contact_name",
            field=models.CharField(
                default="", help_text="Name of emergency contact person", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="emergency_contact_phone",
            field=models.CharField(
                default="",
                help_text="Emergency contact phone number",
                max_length=22,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="emergency_contact_relationship",
            field=models.CharField(
                default="",
                help_text="Relationship with emergency contact person",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="employee_id",
            field=models.CharField(
                default="",
                help_text="School-issued employee ID",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update timestamp"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="qualification",
            field=models.TextField(
                default="", help_text="Academic and professional qualifications"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly salary amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("on_leave", "On Leave"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                ],
                default="active",
                help_text="Current employment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="ID_number",
            field=models.CharField(
                help_text="National ID number or passport number",
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ID number must be 14 characters long and contain only uppercase letters and numbers.",
                        regex="^[A-Z0-9]{14}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="class_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nursery", "Nursery"),
                    ("primary_1", "Primary One"),
                    ("primary_2", "Primary Two"),
                    ("primary_3", "Primary Three"),
                    ("primary_4", "Primary Four"),
                    ("primary_5", "Primary Five"),
                    ("primary_6", "Primary Six"),
                ],
                help_text="Primary class assigned to teacher",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("administration", "Administration"),
                    ("Studies", "Studies"),
                    ("kitchen", "Kitchen"),
                    ("security", "Security"),
                    ("medical", "Medical"),
                    ("library", "Library"),
                    ("other", "Other"),
                ],
                help_text="Department for non-teaching staff",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(
                help_text="Official email address", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(
                help_text="Full name of the staff member", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Staff member's photograph",
                null=True,
                upload_to="staff_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("director", "Director"),
                    ("cleaner", "Cleaner"),
                    ("cook", "Cook"),
                    ("admin", "Admin Staff"),
                    ("librarian", "Librarian"),
                    ("nurse", "School Nurse"),
                    ("security", "Security"),
                    ("other", "Other"),
                ],
                default="teacher",
                help_text="Staff member's role in the school",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                help_text="Gender of the staff member",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="subjects_handled",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects taught by the teacher",
                to="benedict_school.subject",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="tel_no",
            field=models.CharField(
                help_text="Contact phone number",
                max_length=22,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="work_schedule",
            field=models.CharField(
                blank=True,
                help_text="Working hours/shift information",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total years of professional experience",
                null=True,
            ),
        ),
    ]
