# Generated by Django 5.1.1 on 2025-01-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0011_alter_staff_options_staff_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="employee_id",
            field=models.CharField(
                default="", help_text="School-issued employee ID", max_length=20
            ),
        ),
    ]
