# Generated by Django 5.1.1 on 2025-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0012_alter_staff_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="employee_id",
            field=models.CharField(
                default="",
                help_text="School-issued employee ID",
                max_length=20,
                unique=True,
            ),
        ),
    ]
