# Generated by Django 5.1.1 on 2025-01-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0016_remove_child_status_remove_parent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("alumni", "Alumni")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("alumni", "Alumni")],
                default="active",
                max_length=20,
            ),
        ),
    ]
