# Generated by Django 5.1.1 on 2025-01-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0017_child_status_parent_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="subjects_handled",
        ),
        migrations.AddField(
            model_name="staff",
            name="subject_handled",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject taught by the teacher, only one subject allowed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="benedict_school.subject",
            ),
        ),
    ]
