# Generated by Django 5.1.1 on 2025-01-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0018_remove_staff_subjects_handled_staff_subject_handled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="subject_handled",
            field=models.CharField(
                blank=True,
                choices=[
                    ("english", "English"),
                    ("mathematics", "Mathematics"),
                    ("science", "Science"),
                    ("social_studies", "Social Studies"),
                    ("literacy", "Literacy"),
                    ("literacy_1", "Literacy 1"),
                    ("lieracy_1a", "Literacy 1A"),
                    ("literacy_1b", "Literacy 1B"),
                    ("religous_education", "Religous Education"),
                    ("reading", "Reading"),
                    ("luganda", "Luganda"),
                    ("learning_area_1_5", "Learing Area 1-5"),
                ],
                help_text="Subject taught by the teacher, only one subject allowed.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
