# Generated by Django 5.1.1 on 2025-01-24 19:42

import benedict_school.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benedict_school", "0020_alter_staff_subject_handled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="child",
            old_name="name",
            new_name="full_name",
        ),
        migrations.AddField(
            model_name="parent",
            name="num_children",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("mother", "Mother"),
                    ("father", "Father"),
                    ("guardian", "Guardian"),
                    ("relative", "Relative"),
                ],
                default="father",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pupilapplication",
            name="allergies",
            field=models.CharField(
                choices=[
                    ("none", "No Known Allergies"),
                    ("food", "Food Allergy"),
                    ("medication", "Medication Allergy"),
                    ("environmental", "Environmental Allergy"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pupilapplication",
            name="allergy_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pupilapplication",
            name="emergency_contact_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pupilapplication",
            name="emergency_contact_phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="pupilapplication",
            name="medical_conditions",
            field=models.TextField(
                blank=True, help_text="List any existing medical conditions", null=True
            ),
        ),
        migrations.AddField(
            model_name="pupilapplication",
            name="previous_school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pupilapplication",
            name="special_needs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="parent",
            field=models.ForeignKey(
                limit_choices_to=benedict_school.models.limit_children_to_four,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="benedict_school.parent",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="study_class",
            field=models.CharField(
                choices=[
                    ("baby_class", "Baby Class"),
                    ("middle_class", "Middle class"),
                    ("top_class", "Top class"),
                    ("primary_one", "Primary one"),
                    ("primary_two", "Primary two"),
                    ("primary_three", "Primary three"),
                    ("primary_four", "Primary four"),
                    ("primary_five", "Primary five"),
                    ("primary_six", "Primary six"),
                ],
                default="primary_one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applications/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
