# Generated by Django 5.1.1 on 2025-02-04 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "benedict_school",
            "0021_rename_name_child_full_name_parent_num_children_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="num_children",
        ),
        migrations.AlterField(
            model_name="child",
            name="alumni_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parent",
            name="ID_number",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="parent",
            name="alumni_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="allergies",
            field=models.CharField(
                choices=[
                    ("none", "No Known Allergies"),
                    ("food", "Food Allergy"),
                    ("medication", "Medication Allergy"),
                    ("environmental", "Environmental Allergy"),
                    ("other", "Other"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="child",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application",
                to="benedict_school.child",
            ),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applications/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx"]
                    )
                ],
                verbose_name="Application Documents",
            ),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="emergency_contact_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="emergency_contact_phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes or comments", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="previous_school",
            field=models.CharField(
                blank=True,
                help_text="Name of the previous school attended",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pupilapplication",
            name="special_needs",
            field=models.TextField(
                blank=True,
                help_text="Describe any special needs or accommodations required",
                null=True,
            ),
        ),
    ]
