# Generated by Django 5.1.1 on 2025-02-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "benedict_school",
            "0022_remove_parent_num_children_alter_child_alumni_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="num_children",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
